"""Remade some tables

Revision ID: 7e3683f0c070
Revises: f01d13dee9ff
Create Date: 2021-08-30 21:33:52.506360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3683f0c070'
down_revision = 'f01d13dee9ff'
branch_labels = None
depends_on = None

from random import randint

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('bairro', sa.String(length=255), nullable=True))
    change_column_event( 'bairro', '' )
    op.add_column('evento', sa.Column('rua', sa.String(length=255), nullable=True))
    change_column_event( 'rua', '' )
    op.add_column('evento', sa.Column('complemento', sa.String(length=255), nullable=True))
    change_column_event( 'complemento', '' )
    op.add_column('evento', sa.Column('cep', sa.String(length=10), nullable=True))
    change_column_event( 'cep', '' )
    op.add_column('evento', sa.Column('numero', sa.Integer(), nullable=True))
    change_column_event( 'numero', 0 )
    op.drop_column('evento', 'coord_x')
    op.drop_column('evento', 'coord_y')

    op.drop_constraint("usuario_evento_id_usuario_fkey", 'usuario_evento')
    op.drop_constraint("usuario_evento_id_evento_fkey", 'usuario_evento')
    op.create_foreign_key("usuario_evento_id_usuario_fkey", 'usuario_evento', 'usuario', ['id_usuario'], ['id'], ondelete='CASCADE')
    op.create_foreign_key("usuario_evento_id_evento_fkey", 'usuario_evento', 'evento', ['id_evento'], ['id'], ondelete='CASCADE')
    op.drop_constraint("evento_id_criador_fkey", 'evento')
    op.create_foreign_key("evento_id_criador_fkey", 'evento', 'usuario', ['id_criador'], ['id'], ondelete='CASCADE')

    op.execute("DELETE FROM usuario;")
    op.add_column('usuario', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('usuario', sa.Column('openid', sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, 'usuario', ['email', 'openid'])
    op.drop_column('usuario', 'genero')
    # ### end Alembic commands ###

def change_column_event(field, value):
    op.execute(f"UPDATE evento SET {field} = '{value}'")
    op.alter_column(f'evento', field, nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('genero', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_column('usuario', 'openid')
    op.drop_column('usuario', 'email')
    op.add_column('evento', sa.Column('coord_y', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('evento', sa.Column('coord_x', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('evento', 'numero')
    op.drop_column('evento', 'cep')
    op.drop_column('evento', 'complemento')
    op.drop_column('evento', 'rua')
    op.drop_column('evento', 'bairro')
    # ### end Alembic commands ###
