"""Remove idade

Revision ID: 8abbf0f074e9
Revises: 7cf6e35c401e
Create Date: 2021-09-01 16:18:29.946479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8abbf0f074e9'
down_revision = '7cf6e35c401e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE usuario ALTER COLUMN openid TYPE TEXT')
    op.drop_constraint('usuario_email_openid_key', 'usuario', type_='unique')
    op.create_unique_constraint(None, 'usuario', ['openid'])
    op.create_unique_constraint(None, 'usuario', ['email'])
    op.drop_column('usuario', 'idade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario_evento', type_='foreignkey')
    op.drop_constraint(None, 'usuario_evento', type_='foreignkey')
    op.create_foreign_key('usuario_evento_id_usuario_fkey', 'usuario_evento', 'usuario', ['id_usuario'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('usuario_evento_id_evento_fkey', 'usuario_evento', 'evento', ['id_evento'], ['id'], ondelete='CASCADE')
    op.add_column('usuario', sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_constraint(None, 'usuario', type_='unique')
    op.create_unique_constraint('usuario_email_openid_key', 'usuario', ['email', 'openid'])
    op.drop_constraint(None, 'evento', type_='foreignkey')
    op.create_foreign_key('evento_id_criador_fkey', 'evento', 'usuario', ['id_criador'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
