"""Edit unique value

Revision ID: e307f49bb08e
Revises: 7e3683f0c070
Create Date: 2021-08-31 00:09:09.457806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e307f49bb08e'
down_revision = '7e3683f0c070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evento', 'complemento',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario_evento', type_='foreignkey')
    op.drop_constraint(None, 'usuario_evento', type_='foreignkey')
    op.create_foreign_key('usuario_evento_id_evento_fkey', 'usuario_evento', 'evento', ['id_evento'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('usuario_evento_id_usuario_fkey', 'usuario_evento', 'usuario', ['id_usuario'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_constraint(None, 'usuario', type_='unique')
    op.create_unique_constraint('usuario_email_openid_key', 'usuario', ['email', 'openid'])
    op.drop_constraint(None, 'evento', type_='foreignkey')
    op.create_foreign_key('evento_id_criador_fkey', 'evento', 'usuario', ['id_criador'], ['id'], ondelete='CASCADE')
    op.alter_column('evento', 'complemento',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
